"""updated post.slug from slub to slug

Revision ID: 3c5a3e916778
Revises: 5ba28bde4b99
Create Date: 2023-02-10 14:05:34.596477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c5a3e916778'
down_revision = '5ba28bde4b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=300), nullable=True))
        batch_op.drop_column('slub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slub', mysql.VARCHAR(collation='utf8mb4_general_ci', length=300), nullable=True))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
